M48
; DRILL file {KiCad (6.99.0-3907-g11dc5424cb)} date Tue Oct 18 10:11:50 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-18T10:11:50+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.99.0-3907-g11dc5424cb)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1969
%
G90
G05
T1
X6.2Y-3.3
T2
X5.4172Y-3.9774
X6.9842Y-3.9695
T3
X6.2007Y-3.9656
T0
M30
